on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

name: Generate Securities List
permissions:
  contents: write
  pull-requests: write

jobs:
  generate-securities-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: 1.x

      - name: Generate securities list
        run: go run ./scripts/generate_securities.go && go fmt ./twstock/securities_GENERATED.go

      - name: Check securities list changed
        id: check_list_changed
        shell: bash
        run: git diff --exit-code ./twstock/securities_GENERATED.go || echo "changed=1" >> $GITHUB_OUTPUT

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        if: steps.check_list_changed.outputs.changed == 1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request
        id: cpr
        if: steps.check_list_changed.outputs.changed == 1
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 #v7.0.11
        with:
          token: ${{ secrets.PAT }}
          committer: renovate[bot] <renovatebot@bung.cc>
          author: renovate[bot] <renovatebot@bung.cc>
          commit-message: "[Scheduled] Update securities list"
          title: "[Scheduled] Update securities list"
          body: |
            Auto-generated by [create-pull-request][1]
            ---
            [1]: https://github.com/peter-evans/create-pull-request
          branch: cron-generate-securities-list
          delete-branch: true
          labels: GitHub Actions
          assignees: miles170
